title: diasna.uk
email: dias.arifin@gmail.com
description: >- 
  A clean and modern portfolio showcasing projects and professional timeline.
  Built with Jekyll, Tailwind CSS, and ScrollReveal.js for smooth animations.
baseurl: "" 
url: "http://diasna.uk"
linkedin_username: diaxz
github_username:  diasna

# Build settings
plugins:
  - jekyll-feed