title: Ioters
email: dias.arifin@gmail.com
author: Dias Nurul Arifin
description: >- 
  Website untuk berbagi pengalaman seputar programming, microcontroller dan IoT.
baseurl: "/"
url: "https://diasna.github.io"
github_username: diasna

theme: minima
plugins:
  - jekyll-feed